image: Visual Studio 2017
version: 0.1.{build}
pull_requests:
  do_not_increment_build_number: true
configuration:
- Debug
- Release
clone_folder: c:\dev\networkit
before_build:
- cmd: >-
    echo Running cmake...

    cd c:\dev\networkit

    git submodule update --init --recursive

    md build

    cd build

    cmake -G "Visual Studio 15 Win64" -DNETWORKIT_STATIC=ON -DNETWORKIT_BUILD_TESTS=ON ..
build:
  project: c:\dev\networkit\build\networkit.sln
  parallel: true
  verbosity: minimal
test_script:
- cmd: >-
    cd c:\dev\networkit\build
    
    ctest -V --build-config %CONFIGURATION%
